/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    group1374064128: THREE.Mesh
    group167038055: THREE.Mesh
    group1602184737: THREE.Mesh
    group1190332235: THREE.Mesh
    group627047762: THREE.Mesh
    group2112811785: THREE.Mesh
    group740134887: THREE.Mesh
    group300155229: THREE.Mesh
    group217930424: THREE.Mesh
    group1501086520: THREE.Mesh
    group1762201146: THREE.Mesh
    group702594773: THREE.Mesh
    group1836525285: THREE.Mesh
    group813435182: THREE.Mesh
    group1012330263: THREE.Mesh
    group1746021426: THREE.Mesh
    group1624860735: THREE.Mesh
  }
  materials: {
    mat13: THREE.MeshStandardMaterial
    mat14: THREE.MeshStandardMaterial
    mat12: THREE.MeshStandardMaterial
  }
}

export function Fire(props: GroupProps) {
  const { nodes, materials } = useGLTF('/models/fire.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.group1374064128.geometry}
        material={materials.mat13}
      />
      <mesh
        geometry={nodes.group167038055.geometry}
        material={materials.mat14}
      />
      <mesh
        geometry={nodes.group1602184737.geometry}
        material={materials.mat12}
      />
      <mesh
        geometry={nodes.group1190332235.geometry}
        material={materials.mat14}
      />
      <mesh
        geometry={nodes.group627047762.geometry}
        material={materials.mat13}
      />
      <mesh
        geometry={nodes.group2112811785.geometry}
        material={materials.mat13}
      />
      <mesh
        geometry={nodes.group740134887.geometry}
        material={materials.mat14}
      />
      <mesh
        geometry={nodes.group300155229.geometry}
        material={materials.mat12}
      />
      <mesh
        geometry={nodes.group217930424.geometry}
        material={materials.mat14}
      />
      <mesh
        geometry={nodes.group1501086520.geometry}
        material={materials.mat14}
      />
      <mesh
        geometry={nodes.group1762201146.geometry}
        material={materials.mat13}
      />
      <mesh
        geometry={nodes.group702594773.geometry}
        material={materials.mat13}
      />
      <mesh
        geometry={nodes.group1836525285.geometry}
        material={materials.mat13}
      />
      <mesh
        geometry={nodes.group813435182.geometry}
        material={materials.mat14}
      />
      <mesh
        geometry={nodes.group1012330263.geometry}
        material={materials.mat12}
      />
      <mesh
        geometry={nodes.group1746021426.geometry}
        material={materials.mat13}
      />
      <mesh
        geometry={nodes.group1624860735.geometry}
        material={materials.mat14}
      />
    </group>
  )
}
