/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    misc_kettle_cover_Cylinder018: THREE.Mesh
    misc_kettle_nozzle_Cylinder019: THREE.Mesh
    misc_kettle_Cylinder017: THREE.Mesh
  }
  materials: {
    ['Solid.151']: THREE.MeshStandardMaterial
  }
}

export function Kettle(props: GroupProps) {
  const { nodes, materials } = useGLTF('/models/kettle.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.misc_kettle_cover_Cylinder018.geometry}
        material={materials['Solid.151']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.misc_kettle_nozzle_Cylinder019.geometry}
        material={materials['Solid.151']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.misc_kettle_Cylinder017.geometry}
        material={materials['Solid.151']}
      />
    </group>
  )
}
