/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    appliance_stove_knob002_Cube283: THREE.Mesh
    appliance_stove_knob001_Cube284: THREE.Mesh
    appliance_stove001_Cube282: THREE.Mesh
  }
  materials: {
    ['Solid.087']: THREE.MeshStandardMaterial
  }
}

export function Stove(props: GroupProps) {
  const { nodes, materials } = useGLTF(
    '/models/stove.glb',
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.appliance_stove_knob002_Cube283.geometry}
        material={materials['Solid.087']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.appliance_stove_knob001_Cube284.geometry}
        material={materials['Solid.087']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.appliance_stove001_Cube282.geometry}
        material={materials['Solid.087']}
      />
    </group>
  )
}
